seo:
  site_name: Lucian Baba
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social:
  instagram_url:
  facebook_url:
  email_address:
  phone_number:
  