seo:
  site_name: Lucian Baba
  title: Lucian Baba
  description:
  keywords:
  social_image:
  author:
social:
  instagram_url: https://www.instagram.com/
  facebook_url: https://www.facebook.com/laurentiulucian.baba
  email_address: lucianlaurentiubaba@gmail.com
  phone_number: 742381743