seo:
  site_name: Lucian Baba
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social:
  instagram_url: https://www.instagram.com/alexionitaaa/
  facebook_url: https://www.facebook.com/laurentiulucian.baba
  email_address: lucianbaba@gmail.com
  phone_number: 0738454720
